name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v3

      # LINT
      - name: Lint Python
        run: |
          pip install flake8  
          pip install -r api/requirements.txt 
          flake8 .

      - name: Lint JS
        run: |
          cd frontend
          npm install eslint@8 --save-dev
          npm install
          npx eslint .

      - name: Lint Docker
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x hadolint
          ./hadolint api/Dockerfile

      # TEST
      - name: Run Tests
        working-directory: api
        run: |
          pip install pytest pytest-cov -r requirements.txt
          pytest tests/test_prod.py --cov=. --cov-report=xml --cov-report=term --cov-report=term-missing

          
      - uses: actions/upload-artifact@v4
        with:
           name: coverage-report
           path: api/coverage.xml

      # BUILD
      - name: Build Images
        run: |
          IMAGE=localhost:5000/api:${{ github.sha }}
          IMAGE_LATEST=localhost:5000/api:latest
          docker build -t $IMAGE -t $IMAGE_LATEST ./api
          docker push $IMAGE
          docker push $IMAGE_LATEST

      # SECURITY
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: 'localhost:5000/api:latest'
            format: 'sarif'
            output: 'trivy-results.sarif'
            exit-code: '1'
            ignore-unfixed: true
            severity: 'CRITICAL'
      - name: Upload SARIF artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif
          path: trivy-results.sarif

      # INTEGRATION
      - name: Integration Test
        run: |
          docker-compose up -d
          sleep 10
          curl -X POST http://localhost:3000
          docker-compose down
  deploy:
    runs-on: ubuntu-latest                                                                      
    needs: pipeline
    if: github.ref == 'refs/heads/main'
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Docker
          uses: docker/setup-buildx-action@v2
          
        - name: Run deployment script
          run: |
            chmod +x scripts/deploy.sh
            ./scripts/deploy.sh